site_name: Quokka
site_description: A Fast and Accurate Binary Exporter
repo_url: "https://github.com/quarkslab/quokka"
repo_name: "quarkslab/quokka"

theme:
  name: material
  logo: img/logo.png
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

nav:
  - Home: README.md
  - Installation: installation.md
  - Usage: usage.md
  - Features: features.md
  - Tutorial:
      - First step: tutorial/00_intro.md
      - Binary loading: tutorial/01_load.md
      - Functions: tutorial/02_functions.md
      - Blocks: tutorial/03_blocks.md
      - Instructions: tutorial/04_instructions.md
      - References: tutorial/05_references.md
      - Other: tutorial/06_other.md
      - Going Further: tutorial/07_solving.md
  - C++ Reference: reference/cpp/
  - Python Reference: reference/python/
  - Examples: example.md
  - Philosophy: philosophy.md
  - Roadmap: roadmap.md
  - Developers:
      - Contributing: contributing.md
      - Tips & Tricks: dev.md
  - FAQ: FAQ.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - autorefs
  - search
  - gen-files:
      scripts:
        - docs/gen_ref_pages.py
  - literate-nav
  - mkdocstrings:
      watch:
        - bindings/python/quokka
  - mkdocs-simple-hooks:
      hooks:
        on_post_build: "docs.doxygen:generate_cpp_documentation"