name: quokka-build

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12

      - name: Install Ninja (Linux only)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Prepare build environment (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        env:
          IDA_SDK_VERSION: idasdk80
          IDA_SDK_PASSWORD: ${{ secrets.IDA_SDK80_PASSWORD }}
          CMAKE_BUILD_DIR: build80
        run: |
          [ ! -d third_party/$IDA_SDK_VERSION ] && unzip -d third_party -P $IDA_SDK_PASSWORD third_party/$IDA_SDK_VERSION.zip
          [ -f third_party/$IDA_SDK_VERSION/include/regex.h ] && mv third_party/$IDA_SDK_VERSION/include/regex.h third_party/$IDA_SDK_VERSION/include/regex.bak
          cmake -B $CMAKE_BUILD_DIR -S $GITHUB_WORKSPACE -G Ninja -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DIdaSdk_ROOT_DIR=${GITHUB_WORKSPACE}/third_party/$IDA_SDK_VERSION
      
      - name: Prepare build environment (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        env:
          IDA_SDK_VERSION: idasdk80
          IDA_SDK_PASSWORD: ${{ secrets.IDA_SDK80_PASSWORD }}
          CMAKE_BUILD_DIR: build80
        run: |
          7z x -p${IDA_SDK_PASSWORD} -y -othird_party third_party\${IDA_SDK_VERSION}.zip
          rm third_party\${IDA_SDK_VERSION}\regex.h
          cmake -B $CMAKE_BUILD_DIR -S $GITHUB_WORKSPACE -DIdaSdk_ROOT_DIR=${GITHUB_WORKSPACE}/third_party/${IDA_SDK_VERSION}

      - name: Build
        env:
          CMAKE_BUILD_DIR: build80
        run: |
          cmake --build $CMAKE_BUILD_DIR --config $BUILD_TYPE

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        env:
          CMAKE_BUILD_DIR: build80
        with:
          name: idaplugin-artifacts
          path: $CMAKE_BUILD_DIR/quokka-install/*
