name: Quokka Python Package

on:
  push:
    branches:
      - main

jobs:
  python-test:
    name: "Python package test"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install '.[test]'
    - name: Tests
      run: pytest tests/python
